language: scala
scala:
  - 2.11.7
env:
  - ACTIVATOR_VERSION=2.5.8
script:
  - sbt test
jdk:
  - oraclejdk8
services:
  - mysql
sudo: true
before_script:
  - bash .travis.install-mysql-5.7.sh 
  - mysql -u root -e "CREATE DATABASE mydatabase;"